on:
  push:
    branches:
      - main
      # - feature/githubActionBuild
  pull_request:
    branches:
      - main
      # - feature/githubActionBuild

name: Compile

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release